import * as vscode from 'vscode';
import { VivadoProject } from '../../models/vivado-project';
import { VivadoRun } from '../../models/vivado-run';
import {
    ResolvedVivadoRunCommand,
    resolveVivadoRunTarget,
    VivadoRunCommandTarget,
    VivadoTclActionDefinition,
} from './run-command';
import { vivadoBuildTclActionDefinitions } from './tcl-actions';

const commandId = 'vscode-vivado.projects.previewGeneratedTcl';

export interface ResolvedVivadoTclPreviewAction extends ResolvedVivadoRunCommand {
    definition: VivadoTclActionDefinition;
}

export interface VivadoTclPreviewQuickPickItem extends vscode.QuickPickItem {
    action: ResolvedVivadoTclPreviewAction;
}

export interface PreviewVivadoGeneratedTclDependencies {
    showQuickPick: (
        items: VivadoTclPreviewQuickPickItem[],
        options: vscode.QuickPickOptions,
    ) => Thenable<VivadoTclPreviewQuickPickItem | undefined>;
    openTextDocument: (options: { language: string; content: string }) => Thenable<vscode.TextDocument>;
    showTextDocument: (
        document: vscode.TextDocument,
        options?: vscode.TextDocumentShowOptions,
    ) => Thenable<vscode.TextEditor>;
    showErrorMessage: (message: string) => Thenable<string | undefined>;
}

export interface PreviewVivadoGeneratedTclOptions {
    actionDefinitions?: readonly VivadoTclActionDefinition[];
    dependencies?: Partial<PreviewVivadoGeneratedTclDependencies>;
}

export default async function previewVivadoGeneratedTcl(
    target: VivadoProject | VivadoRunCommandTarget | undefined,
    options: PreviewVivadoGeneratedTclOptions = {},
): Promise<boolean> {
    const dependencies = resolveDependencies(options.dependencies);

    try {
        const actions = resolveVivadoTclPreviewActions(target, options.actionDefinitions);
        const action = await choosePreviewAction(actions, dependencies);

        if (!action) {
            return false;
        }

        const document = await dependencies.openTextDocument({
            language: 'tcl',
            content: buildVivadoTclPreviewContent(action.definition, action.project, action.run),
        });
        await dependencies.showTextDocument(document, { preview: false });
        return true;
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        await dependencies.showErrorMessage(message);
        return false;
    }
}

export function resolveVivadoTclPreviewActions(
    target: VivadoProject | VivadoRunCommandTarget | undefined,
    actionDefinitions: readonly VivadoTclActionDefinition[] = vivadoBuildTclActionDefinitions,
): ResolvedVivadoTclPreviewAction[] {
    if (!target) {
        throw new Error('Select a Vivado project or run in the Projects view before previewing generated TCL.');
    }

    const actions: ResolvedVivadoTclPreviewAction[] = [];

    for (const definition of actionDefinitions) {
        try {
            actions.push({
                definition,
                ...resolveVivadoRunTarget(target, definition),
            });
        } catch {
            // Unsupported actions are filtered out so the preview can offer only valid choices.
        }
    }

    if (actions.length === 0) {
        throw new Error('No generated TCL actions are available for the selected Vivado item.');
    }

    return actions;
}

export function buildVivadoTclPreviewContent(
    definition: VivadoTclActionDefinition,
    project: VivadoProject,
    run: VivadoRun,
): string {
    const header = [
        '# Generated by VS Code Vivado.',
        '# Preview only. This script has not been executed.',
        `# Action: ${definition.title}`,
        `# Project: ${project.name}`,
        `# Run: ${run.name}`,
    ];

    if (definition.destructive) {
        header.push('# Destructive: Yes');
    }

    const body = definition.buildTcl(project, run);
    const normalizedBody = body.endsWith('\n') ? body : `${body}\n`;

    return `${header.join('\n')}\n\n${normalizedBody}`;
}

async function choosePreviewAction(
    actions: ResolvedVivadoTclPreviewAction[],
    dependencies: PreviewVivadoGeneratedTclDependencies,
): Promise<ResolvedVivadoTclPreviewAction | undefined> {
    if (actions.length === 1) {
        return actions[0];
    }

    const items = actions.map(action => ({
        label: action.definition.title,
        description: `${action.project.name}/${action.run.name}`,
        action,
    }));
    const selected = await dependencies.showQuickPick(items, {
        placeHolder: 'Select the Vivado action to preview',
        title: 'Preview Generated TCL',
    });

    return selected?.action;
}

function resolveDependencies(
    dependencies: Partial<PreviewVivadoGeneratedTclDependencies> = {},
): PreviewVivadoGeneratedTclDependencies {
    return {
        showQuickPick: (items, options) => vscode.window.showQuickPick(items, options),
        openTextDocument: options => vscode.workspace.openTextDocument(options),
        showTextDocument: (document, options) => vscode.window.showTextDocument(document, options),
        showErrorMessage: message => vscode.window.showErrorMessage(message),
        ...dependencies,
    };
}

export { commandId as previewVivadoGeneratedTclCommandId };
