/**
 * Tests for visible Vivado TCL script generation.
 * Covers #6 - Generate visible TCL for extension-driven Vivado actions.
 */
import * as assert from 'assert';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as vscode from 'vscode';
import {
    buildVivadoTclFileContent,
    buildVivadoTclFileName,
    resolveVivadoTclDirectory,
    writeVisibleVivadoTclScript,
} from '../../utils/vivado-tcl';

const createdTempDirectories: string[] = [];

function makeTempDirectory(prefix: string): string {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
    createdTempDirectories.push(directory);
    return directory;
}

function cleanupTempDirectories(): void {
    while (createdTempDirectories.length > 0) {
        const directory = createdTempDirectories.pop();
        if (directory) {
            fs.rmSync(directory, { recursive: true, force: true });
        }
    }
}

suite('Vivado TCL script visibility', () => {
    teardown(() => {
        cleanupTempDirectories();
    });

    test('resolves generated TCL under the configured workspace-relative directory', () => {
        const startPath = vscode.Uri.file(path.join(os.tmpdir(), 'vivado-project'));
        const directory = resolveVivadoTclDirectory(startPath, {
            generatedTclDirectory: '.vscode-vivado/tcl',
        });

        assert.strictEqual(
            directory.fsPath,
            path.join(startPath.fsPath, '.vscode-vivado', 'tcl')
        );
    });

    test('supports an absolute generated TCL directory', () => {
        const absoluteDirectory = makeTempDirectory('vivado-tcl-absolute-');
        const directory = resolveVivadoTclDirectory(vscode.Uri.file('/ignored'), {
            generatedTclDirectory: absoluteDirectory,
        });

        assert.strictEqual(directory.fsPath.toLowerCase(), absoluteDirectory.toLowerCase());
    });

    test('builds deterministic script names from task names and UTC time', () => {
        const now = new Date(Date.UTC(2026, 3, 19, 0, 50, 1, 23));

        assert.strictEqual(
            buildVivadoTclFileName('Run Synthesis: top', now),
            '20260419-005001-023-run-synthesis-top.tcl'
        );
        assert.strictEqual(
            buildVivadoTclFileName('   ', now),
            '20260419-005001-023-vivado-task.tcl'
        );
    });

    test('adds rerun metadata without dropping the TCL body', () => {
        const content = buildVivadoTclFileContent('open_project project.xpr\nexit', {
            taskName: 'Run Synthesis',
            workingDirectory: '/workspace/project',
            rerunCommand: "vivado -mode batch -source '/workspace/project/.vscode-vivado/tcl/run.tcl'",
        });

        assert.ok(content.includes('# Generated by VS Code Vivado.'));
        assert.ok(content.includes('# Task: Run Synthesis'));
        assert.ok(content.includes('# Working directory: /workspace/project'));
        assert.ok(content.includes('# Rerun command:'));
        assert.ok(content.endsWith('open_project project.xpr\nexit\n'));
    });

    test('writes the visible TCL script to disk', () => {
        const startPath = vscode.Uri.file(makeTempDirectory('vivado-project-'));
        const tclDirectory = vscode.Uri.file(makeTempDirectory('vivado-tcl-'));
        const script = writeVisibleVivadoTclScript({
            startPath,
            taskName: 'Run Implementation',
            tcl: 'launch_runs impl_1\nwait_on_run impl_1\nexit',
            settings: { generatedTclDirectory: '.vscode-vivado/tcl' },
            rerunCommand: 'vivado -mode batch -source run-impl.tcl',
            tclDirectory,
            now: new Date(Date.UTC(2026, 3, 19, 1, 2, 3, 4)),
        });

        assert.strictEqual(
            path.basename(script.uri.fsPath),
            '20260419-010203-004-run-implementation.tcl'
        );
        assert.strictEqual(fs.readFileSync(script.uri.fsPath, 'utf8'), script.content);
        assert.ok(script.content.includes('vivado -mode batch -source run-impl.tcl'));
        assert.ok(script.content.includes('launch_runs impl_1'));
    });
});
