import fs from 'fs';
import path from 'path';
import * as vscode from 'vscode';
import { VivadoSettings } from './vivado-settings';

export interface VivadoTclWriteOptions {
    startPath: vscode.Uri;
    taskName: string;
    tcl: string;
    settings: Pick<VivadoSettings, 'generatedTclDirectory'>;
    rerunCommand: string;
    tclDirectory?: vscode.Uri;
    uri?: vscode.Uri;
    now?: Date;
}

export interface VivadoTclScript {
    uri: vscode.Uri;
    content: string;
}

export function writeVisibleVivadoTclScript(options: VivadoTclWriteOptions): VivadoTclScript {
    const directory = options.tclDirectory ?? resolveVivadoTclDirectory(options.startPath, options.settings);
    const uri = options.uri ?? buildVivadoTclFileUri(directory, options.taskName, options.now);
    const content = buildVivadoTclFileContent(options.tcl, {
        taskName: options.taskName,
        workingDirectory: options.startPath.fsPath,
        rerunCommand: options.rerunCommand,
    });

    fs.mkdirSync(path.dirname(uri.fsPath), { recursive: true });
    fs.writeFileSync(uri.fsPath, content);

    return { uri, content };
}

export function buildVivadoTclFileUri(directory: vscode.Uri, taskName: string, now?: Date): vscode.Uri {
    return vscode.Uri.file(path.join(directory.fsPath, buildVivadoTclFileName(taskName, now)));
}

export function resolveVivadoTclDirectory(
    startPath: vscode.Uri,
    settings: Pick<VivadoSettings, 'generatedTclDirectory'>,
): vscode.Uri {
    if (path.isAbsolute(settings.generatedTclDirectory)) {
        return vscode.Uri.file(settings.generatedTclDirectory);
    }

    return vscode.Uri.joinPath(startPath, settings.generatedTclDirectory);
}

export function buildVivadoTclFileName(taskName: string, now: Date = new Date()): string {
    return `${formatTimestamp(now)}-${slugifyTaskName(taskName)}.tcl`;
}

export interface VivadoTclFileContentMetadata {
    taskName: string;
    workingDirectory: string;
    rerunCommand: string;
}

export function buildVivadoTclFileContent(tcl: string, metadata: VivadoTclFileContentMetadata): string {
    const normalizedTcl = tcl.endsWith('\n') ? tcl : `${tcl}\n`;

    return [
        '# Generated by VS Code Vivado.',
        `# Task: ${singleLine(metadata.taskName)}`,
        `# Working directory: ${singleLine(metadata.workingDirectory)}`,
        '# Rerun command:',
        `#   ${singleLine(metadata.rerunCommand)}`,
        '',
        normalizedTcl,
    ].join('\n');
}

function formatTimestamp(now: Date): string {
    return [
        now.getUTCFullYear().toString().padStart(4, '0'),
        (now.getUTCMonth() + 1).toString().padStart(2, '0'),
        now.getUTCDate().toString().padStart(2, '0'),
        '-',
        now.getUTCHours().toString().padStart(2, '0'),
        now.getUTCMinutes().toString().padStart(2, '0'),
        now.getUTCSeconds().toString().padStart(2, '0'),
        '-',
        now.getUTCMilliseconds().toString().padStart(3, '0'),
    ].join('');
}

function slugifyTaskName(taskName: string): string {
    const slug = taskName
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9._-]+/g, '-')
        .replace(/^-+|-+$/g, '');

    return slug || 'vivado-task';
}

function singleLine(value: string): string {
    return value.replace(/[\r\n]+/g, ' ');
}
